# Generated by Django 5.1.6 on 2025-02-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.JSONField()),
                ('time', models.CharField(max_length=50)),
                ('meal_type', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('side_image', models.URLField()),
                ('favourites', models.IntegerField(default=0)),
                ('steps', models.JSONField()),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
