# Generated by Django 5.1.6 on 2025-02-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='side_image',
            new_name='sideImage',
        ),
    ]
